name: Senior Verivication Assesment 

on:
  push:
    branches:
      - main
        develop
  pull_request:
    branches:
      - main
        develop
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.9.5 


  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform init
      - run: terraform -chdir=terraform validate
      - run: terraform -chdir=terraform fmt -check
      - if: github.event_name == 'pull_request'
        run: terraform -chdir=terraform plan
      - if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with: { role-to-assume: arn:aws:iam::767398146991:role/sva-role, aws-region: eu-west-2 }
      - if: github.ref == 'refs/heads/main'
        run: terraform -chdir=terraform apply -auto-approve
  ansible:
    needs: terraform
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with: { role-to-assume: arn:aws:iam::767398146991:role/sva-role, aws-region: eu-west-2 }
      - run: pip install ansible
      - run: ansible-playbook -i ansible/inventory.yml
